server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: relayer-example
  static_configs:
  - targets:
      - relayer-example
    labels:
      job: relayer-example
      __path__: /logs/*.log